/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 Apple.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function AppleModel(props) {
  const { nodes, materials } = useGLTF("/models/Apple.glb");
  return (
    <group {...props} dispose={null} scale={6} position={[3, 0, 0]}>
      <mesh geometry={nodes.Cube020.geometry} material={materials.DarkRed} />
      <mesh
        geometry={nodes.Cube020_1.geometry}
        material={materials.DarkBrown}
      />
      <mesh
        geometry={nodes.Cube020_2.geometry}
        material={materials.DarkGreen}
      />
    </group>
  );
}

useGLTF.preload("/Apple.glb");
