/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 burger.glb 
*/

import React, { forwardRef, useEffect, useRef, useState } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useGSAP } from "@gsap/react";
import gsap from "gsap";

export const BurgerAnim = forwardRef((props, ref) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/burger.glb");
  const { actions } = useAnimations(animations, ref);
  const [maxTime, setMaxtime] = useState(5);

  useEffect(() => {
    if (actions) {
      // Play all animations
      Object.values(actions).forEach((action) => {
        action.play();
        if (action.duration > maxTime) {
          setMaxtime(action.duration);
        }
      });
    }
  }, [actions]);
  return (
    <group ref={ref} {...props} dispose={null} scale={0}>
      <group name="Scene">
        <group name="Empty001" position={[0, 1.218, 0]}>
          <group
            name="Empty"
            position={[0, -1.218, 0]}
            rotation={[-Math.PI, 0.657, -Math.PI]}
          >
            <group name="BurgerLarge" rotation={[0, -0.087, 0]} scale={0.47}>
              <mesh
                name="Plane005"
                geometry={nodes.Plane005.geometry}
                material={materials.LightGreen}
              />
              <mesh
                name="Plane005_1"
                geometry={nodes.Plane005_1.geometry}
                material={materials.Yellow}
              />
              <mesh
                name="Plane005_2"
                geometry={nodes.Plane005_2.geometry}
                material={materials.Brown}
              />
              <mesh
                name="Plane005_3"
                geometry={nodes.Plane005_3.geometry}
                material={materials.Red}
              />
              <mesh
                name="Plane005_4"
                geometry={nodes.Plane005_4.geometry}
                material={materials.LightYellow}
              />
              <mesh
                name="Plane005_5"
                geometry={nodes.Plane005_5.geometry}
                material={materials.White}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
});

useGLTF.preload("/burger.glb");
