/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 BurgerLarge.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function BurgerLarge(props) {
  const { nodes, materials } = useGLTF("/models/BurgerLarge.glb");
  return (
    <group {...props} dispose={null} scale={3} position={[3, 0.3, 0]}>
      <mesh
        geometry={nodes.Plane005.geometry}
        material={materials.LightGreen}
      />
      <mesh geometry={nodes.Plane005_1.geometry} material={materials.Yellow} />
      <mesh geometry={nodes.Plane005_2.geometry} material={materials.Brown} />
      <mesh geometry={nodes.Plane005_3.geometry} material={materials.Red} />
      <mesh
        geometry={nodes.Plane005_4.geometry}
        material={materials.LightYellow}
      />
      <mesh geometry={nodes.Plane005_5.geometry} material={materials.White} />
    </group>
  );
}

useGLTF.preload("/BurgerLarge.glb");
