/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 ChickenLeg.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function ChickenLeg(props) {
  const { nodes, materials } = useGLTF("/models/ChickenLeg.glb");
  return (
    <group
      {...props}
      dispose={null}
      position={[3, 0, 0]}
      scale={4}
      rotation-z={(-Math.PI * 45) / 180}
    >
      <mesh geometry={nodes.Cube048.geometry} material={materials.DarkBrown} />
      <mesh geometry={nodes.Cube048_1.geometry} material={materials.Beige} />
    </group>
  );
}

useGLTF.preload("/ChickenLeg.glb");
