/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 CookingPot2_Soup.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function CookingPot(props) {
  const { nodes, materials } = useGLTF("/models/CookingPot2_Soup.glb");
  return (
    <group
      {...props}
      dispose={null}
      position={[3, -0.5, 0]}
      scale={2}
      rotation-x={(Math.PI / 180) * 10}
    >
      <mesh geometry={nodes.Cylinder016.geometry} material={materials.Grey} />
      <mesh
        geometry={nodes.Cylinder016_1.geometry}
        material={materials.Brown}
      />
    </group>
  );
}

useGLTF.preload("/CookingPot2_Soup.glb");
