/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 Cupcake.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Cupcake(props) {
  const { nodes, materials } = useGLTF("/models/Cupcake.glb");
  return (
    <group {...props} dispose={null} scale={4} position={[3, -1, 0]}>
      <mesh
        geometry={nodes.Cylinder026.geometry}
        material={materials.LightYellow}
      />
      <mesh geometry={nodes.Cylinder026_1.geometry} material={materials.Pink} />
      <mesh
        geometry={nodes.Cylinder026_2.geometry}
        material={materials.DarkBrown}
      />
    </group>
  );
}

useGLTF.preload("/Cupcake.glb");
