/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 earth.glb 
*/

import React, { useRef } from "react";
import { OrbitControls, useGLTF } from "@react-three/drei";

export function EarthModel(props) {
  const { nodes, materials } = useGLTF("/models/earth.glb");
  return (
    <group {...props} dispose={null} rotation-y={-Math.PI / 4} scale={30}>
      <axesHelper />
      <OrbitControls />
      <mesh
        geometry={nodes.wiree002.geometry}
        material={materials["instances grid.001"]}
        scale={0.305}
      >
        <mesh
          geometry={nodes.Plane345.geometry}
          material={materials["material.001"]}
          position={[0.413, -0.267, 0.861]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane346.geometry}
          material={materials["material.001"]}
          position={[0.408, -0.285, 0.851]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane347.geometry}
          material={materials["material.001"]}
          position={[0.427, -0.25, 0.868]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane348.geometry}
          material={materials["material.001"]}
          position={[0.406, -0.287, 0.862]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane349.geometry}
          material={materials["material.001"]}
          position={[0.413, -0.282, 0.862]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane350.geometry}
          material={materials["material.001"]}
          position={[0.372, -0.324, 0.866]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane351.geometry}
          material={materials["material.001"]}
          position={[0.592, 0.007, 0.795]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane352.geometry}
          material={materials["material.001"]}
          position={[0.34, 0.16, 0.917]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane353.geometry}
          material={materials["material.001"]}
          position={[0.399, -0.293, 0.865]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane354.geometry}
          material={materials["material.001"]}
          position={[0.394, -0.305, 0.862]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane355.geometry}
          material={materials["material.001"]}
          position={[0.382, -0.314, 0.865]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane356.geometry}
          material={materials["material.001"]}
          position={[0.376, -0.317, 0.866]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane357.geometry}
          material={materials["material.001"]}
          position={[0.41, -0.287, 0.861]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane358.geometry}
          material={materials["material.001"]}
          position={[0.41, -0.274, 0.864]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane359.geometry}
          material={materials["material.001"]}
          position={[0.409, -0.267, 0.868]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane360.geometry}
          material={materials["material.001"]}
          position={[0.422, -0.248, 0.869]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane361.geometry}
          material={materials["material.001"]}
          position={[0.418, -0.254, 0.866]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane362.geometry}
          material={materials["material.001"]}
          position={[0.406, -0.28, 0.865]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane363.geometry}
          material={materials["material.001"]}
          position={[0.376, -0.285, 0.877]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane364.geometry}
          material={materials["material.001"]}
          position={[0.37, -0.284, 0.879]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane365.geometry}
          material={materials["material.001"]}
          position={[0.379, -0.276, 0.879]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane366.geometry}
          material={materials["material.001"]}
          position={[0.39, -0.277, 0.874]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane367.geometry}
          material={materials["material.001"]}
          position={[0.388, -0.285, 0.871]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane368.geometry}
          material={materials["material.001"]}
          position={[0.395, -0.284, 0.868]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane369.geometry}
          material={materials["material.001"]}
          position={[0.401, -0.278, 0.869]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane370.geometry}
          material={materials["material.001"]}
          position={[0.392, -0.272, 0.873]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane371.geometry}
          material={materials["material.001"]}
          position={[0.383, -0.292, 0.871]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane372.geometry}
          material={materials["material.001"]}
          position={[0.41, -0.259, 0.87]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane373.geometry}
          material={materials["material.001"]}
          position={[0.407, -0.253, 0.872]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane374.geometry}
          material={materials["material.001"]}
          position={[0.393, -0.265, 0.876]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane375.geometry}
          material={materials["material.001"]}
          position={[0.391, -0.259, 0.878]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane376.geometry}
          material={materials["material.001"]}
          position={[0.366, -0.275, 0.884]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane377.geometry}
          material={materials["material.001"]}
          position={[0.394, -0.299, 0.864]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane378.geometry}
          material={materials["material.001"]}
          position={[0.385, -0.3, 0.869]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane379.geometry}
          material={materials["material.001"]}
          position={[0.377, -0.299, 0.872]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane380.geometry}
          material={materials["material.001"]}
          position={[0.383, -0.306, 0.867]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane381.geometry}
          material={materials["material.001"]}
          position={[0.585, -0.061, 0.797]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane382.geometry}
          material={materials["material.001"]}
          position={[0.607, -0.063, 0.781]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane383.geometry}
          material={materials["material.001"]}
          position={[0.555, -0.048, 0.819]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane384.geometry}
          material={materials["material.001"]}
          position={[0.39, 0.094, 0.907]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane385.geometry}
          material={materials["material.001"]}
          position={[0.417, 0.057, 0.898]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane386.geometry}
          material={materials["material.001"]}
          position={[0.375, 0.042, 0.918]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane387.geometry}
          material={materials["material.001"]}
          position={[0.389, 0.03, 0.914]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane388.geometry}
          material={materials["material.001"]}
          position={[0.437, -0.011, 0.89]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane389.geometry}
          material={materials["material.001"]}
          position={[0.415, -0.171, 0.886]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane390.geometry}
          material={materials["material.001"]}
          position={[0.351, -0.019, 0.928]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane391.geometry}
          material={materials["material.001"]}
          position={[0.363, 0.075, 0.921]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane392.geometry}
          material={materials["material.001"]}
          position={[0.491, -0.128, 0.852]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane393.geometry}
          material={materials["material.001"]}
          position={[0.642, -0.021, 0.754]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane394.geometry}
          material={materials["material.001"]}
          position={[0.621, -0.072, 0.769]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane395.geometry}
          material={materials["material.001"]}
          position={[0.405, -0.057, 0.904]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane396.geometry}
          material={materials["material.001"]}
          position={[0.635, -0.043, 0.759]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane397.geometry}
          material={materials["material.001"]}
          position={[0.602, -0.027, 0.787]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane398.geometry}
          material={materials["material.001"]}
          position={[0.375, -0.139, 0.909]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane399.geometry}
          material={materials["material.001"]}
          position={[0.364, -0.289, 0.88]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane400.geometry}
          material={materials["material.001"]}
          position={[0.373, -0.218, 0.896]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane401.geometry}
          material={materials["material.001"]}
          position={[0.391, 0.131, 0.901]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane402.geometry}
          material={materials["material.001"]}
          position={[0.522, -0.064, 0.841]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane403.geometry}
          material={materials["material.001"]}
          position={[0.304, -0.086, 0.942]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane404.geometry}
          material={materials["material.001"]}
          position={[0.331, -0.212, 0.915]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane405.geometry}
          material={materials["material.001"]}
          position={[0.461, -0.112, 0.871]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane406.geometry}
          material={materials["material.001"]}
          position={[0.518, -0.024, 0.845]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane407.geometry}
          material={materials["material.001"]}
          position={[0.618, -0.02, 0.773]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane408.geometry}
          material={materials["material.001"]}
          position={[0.649, 0.018, 0.747]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane409.geometry}
          material={materials["material.001"]}
          position={[0.423, -0.205, 0.874]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane410.geometry}
          material={materials["material.001"]}
          position={[0.501, 0.02, 0.855]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane411.geometry}
          material={materials["material.001"]}
          position={[0.418, -0.338, 0.838]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane412.geometry}
          material={materials["material.001"]}
          position={[0.909, -0.06, 0.38]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane413.geometry}
          material={materials["material.001"]}
          position={[0.812, -0.151, 0.545]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane414.geometry}
          material={materials["material.001"]}
          position={[0.918, 0.222, 0.272]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane415.geometry}
          material={materials["material.001"]}
          position={[0.376, 0.554, -0.723]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane416.geometry}
          material={materials["material.001"]}
          position={[-0.775, 0.372, -0.506]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane417.geometry}
          material={materials["material.001"]}
          position={[-0.326, 0.771, 0.535]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane418.geometry}
          material={materials["material.001"]}
          position={[-0.316, 0.789, 0.512]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane419.geometry}
          material={materials["material.001"]}
          position={[-0.391, 0.778, 0.477]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane420.geometry}
          material={materials["material.001"]}
          position={[-0.726, 0.65, 0.208]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane421.geometry}
          material={materials["material.001"]}
          position={[-0.863, 0.415, -0.284]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane422.geometry}
          material={materials["material.001"]}
          position={[-0.524, 0.638, -0.553]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane423.geometry}
          material={materials["material.001"]}
          position={[-0.315, 0.732, -0.589]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane424.geometry}
          material={materials["material.001"]}
          position={[-0.243, 0.735, -0.617]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane425.geometry}
          material={materials["material.001"]}
          position={[-0.346, 0.695, -0.616]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane426.geometry}
          material={materials["material.001"]}
          position={[-0.501, 0.734, -0.443]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane427.geometry}
          material={materials["material.001"]}
          position={[-0.566, 0.679, -0.455]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane428.geometry}
          material={materials["material.001"]}
          position={[-0.334, 0.773, -0.523]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane429.geometry}
          material={materials["material.001"]}
          position={[-0.394, 0.757, -0.501]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane430.geometry}
          material={materials["material.001"]}
          position={[-0.343, 0.752, -0.548]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane431.geometry}
          material={materials["material.001"]}
          position={[-0.288, 0.758, -0.569]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane432.geometry}
          material={materials["material.001"]}
          position={[-0.313, 0.779, -0.527]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane433.geometry}
          material={materials["material.001"]}
          position={[-0.251, 0.781, -0.553]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane434.geometry}
          material={materials["material.001"]}
          position={[-0.17, 0.774, -0.591]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane435.geometry}
          material={materials["material.001"]}
          position={[-0.168, 0.756, -0.613]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane436.geometry}
          material={materials["material.001"]}
          position={[-0.091, 0.764, -0.619]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane437.geometry}
          material={materials["material.001"]}
          position={[-0.061, 0.733, -0.658]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane438.geometry}
          material={materials["material.001"]}
          position={[-0.165, 0.78, -0.585]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane439.geometry}
          material={materials["material.001"]}
          position={[-0.348, 0.789, -0.487]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane440.geometry}
          material={materials["material.001"]}
          position={[-0.01, 0.434, -0.889]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane441.geometry}
          material={materials["material.001"]}
          position={[0.53, 0.716, -0.416]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane442.geometry}
          material={materials["material.001"]}
          position={[0.099, 0.797, 0.576]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane443.geometry}
          material={materials["material.001"]}
          position={[0.063, 0.795, 0.585]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane444.geometry}
          material={materials["material.001"]}
          position={[-0.06, 0.69, 0.709]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane445.geometry}
          material={materials["material.001"]}
          position={[0.019, 0.797, 0.588]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane446.geometry}
          material={materials["material.001"]}
          position={[-0.055, 0.793, 0.59]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane447.geometry}
          material={materials["material.001"]}
          position={[-0.457, 0.51, 0.724]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane448.geometry}
          material={materials["material.001"]}
          position={[0.447, 0.781, 0.4]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane449.geometry}
          material={materials["material.001"]}
          position={[0.405, 0.787, 0.432]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane450.geometry}
          material={materials["material.001"]}
          position={[0.376, 0.795, 0.444]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane451.geometry}
          material={materials["material.001"]}
          position={[0.629, 0.752, -0.056]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane452.geometry}
          material={materials["material.001"]}
          position={[0.65, 0.737, 0.019]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane453.geometry}
          material={materials["material.001"]}
          position={[0.629, 0.754, 0.021]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane454.geometry}
          material={materials["material.001"]}
          position={[0.882, 0.429, 0.006]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane455.geometry}
          material={materials["material.001"]}
          position={[-0.665, 0.724, 0.161]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane456.geometry}
          material={materials["material.001"]}
          position={[-0.57, 0.809, -0.088]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane457.geometry}
          material={materials["material.001"]}
          position={[-0.679, 0.698, -0.205]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane458.geometry}
          material={materials["material.001"]}
          position={[-0.099, -0.655, 0.751]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane459.geometry}
          material={materials["material.001"]}
          position={[-0.726, -0.111, -0.677]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane460.geometry}
          material={materials["material.001"]}
          position={[-0.812, -0.163, -0.565]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane461.geometry}
          material={materials["material.001"]}
          position={[-0.622, 0.209, 0.755]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane462.geometry}
          material={materials["material.001"]}
          position={[-0.681, 0.254, 0.688]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane463.geometry}
          material={materials["material.001"]}
          position={[-0.624, 0.33, 0.702]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane464.geometry}
          material={materials["material.001"]}
          position={[-0.448, -0.859, -0.272]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane465.geometry}
          material={materials["material.001"]}
          position={[-0.483, 0.248, 0.838]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane466.geometry}
          material={materials["material.001"]}
          position={[0.894, -0.294, 0.303]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane467.geometry}
          material={materials["material.001"]}
          position={[0.872, -0.356, 0.304]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane468.geometry}
          material={materials["material.001"]}
          position={[0.892, -0.226, 0.359]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane469.geometry}
          material={materials["material.001"]}
          position={[0.649, -0.466, 0.584]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane470.geometry}
          material={materials["material.001"]}
          position={[0.689, -0.553, 0.453]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane471.geometry}
          material={materials["material.001"]}
          position={[0.849, -0.453, 0.234]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane472.geometry}
          material={materials["material.001"]}
          position={[0.799, -0.488, 0.324]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane473.geometry}
          material={materials["material.001"]}
          position={[0.842, -0.503, 0.132]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane474.geometry}
          material={materials["material.001"]}
          position={[-0.571, 0.519, 0.633]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane475.geometry}
          material={materials["material.001"]}
          position={[-0.769, 0.49, 0.408]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane476.geometry}
          material={materials["material.001"]}
          position={[-0.717, 0.51, 0.469]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane477.geometry}
          material={materials["material.001"]}
          position={[-0.741, 0.509, 0.436]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane478.geometry}
          material={materials["material.001"]}
          position={[0.829, -0.53, -0.113]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane479.geometry}
          material={materials["material.001"]}
          position={[0.817, -0.558, -0.035]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane480.geometry}
          material={materials["material.001"]}
          position={[0.578, -0.811, -0.035]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane481.geometry}
          material={materials["material.001"]}
          position={[0.511, -0.79, -0.327]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane482.geometry}
          material={materials["material.001"]}
          position={[0.5, -0.816, -0.275]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane483.geometry}
          material={materials["material.001"]}
          position={[-0.875, 0.223, 0.434]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane484.geometry}
          material={materials["material.001"]}
          position={[0.929, 0.318, 0.018]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane485.geometry}
          material={materials["material.001"]}
          position={[0.961, 0.131, 0.169]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane486.geometry}
          material={materials["material.001"]}
          position={[0.956, 0.189, 0.105]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane487.geometry}
          material={materials["material.001"]}
          position={[0.954, 0.102, 0.224]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane488.geometry}
          material={materials["material.001"]}
          position={[-0.193, 0.715, -0.653]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane489.geometry}
          material={materials["material.001"]}
          position={[-0.565, 0.689, -0.425]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane490.geometry}
          material={materials["material.001"]}
          position={[0.033, 0.734, 0.66]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane491.geometry}
          material={materials["material.001"]}
          position={[0.772, -0.444, 0.43]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane492.geometry}
          material={materials["material.001"]}
          position={[-0.809, 0.26, 0.524]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane493.geometry}
          material={materials["material.001"]}
          position={[-0.713, 0.382, 0.582]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane494.geometry}
          material={materials["material.001"]}
          position={[0.331, 0.195, 0.915]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane495.geometry}
          material={materials["material.001"]}
          position={[0.26, 0.056, 0.952]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane496.geometry}
          material={materials["material.001"]}
          position={[0.337, 0.333, 0.795]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane497.geometry}
          material={materials["material.001"]}
          position={[-0.057, 0.153, 0.968]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane498.geometry}
          material={materials["material.001"]}
          position={[0.678, 0.166, 0.612]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane499.geometry}
          material={materials["material.001"]}
          position={[-0.534, 0.232, -0.747]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane500.geometry}
          material={materials["material.001"]}
          position={[-0.247, 0.575, -0.612]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane501.geometry}
          material={materials["material.001"]}
          position={[-0.433, 0.79, -0.407]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane502.geometry}
          material={materials["material.001"]}
          position={[-0.636, 0.737, -0.039]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane503.geometry}
          material={materials["material.001"]}
          position={[-0.536, -0.058, 0.79]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane504.geometry}
          material={materials["material.001"]}
          position={[-0.303, 0.194, 0.923]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane505.geometry}
          material={materials["material.001"]}
          position={[-0.299, -0.468, 0.806]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane506.geometry}
          material={materials["material.001"]}
          position={[-0.48, -0.13, -0.827]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane507.geometry}
          material={materials["material.001"]}
          position={[0.239, 0.606, 0.411]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane508.geometry}
          material={materials["material.001"]}
          position={[-0.411, 0.425, 0.789]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane509.geometry}
          material={materials["material.001"]}
          position={[-0.78, -0.246, 0.538]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane510.geometry}
          material={materials["material.001"]}
          position={[-0.657, -0.632, -0.311]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane511.geometry}
          material={materials["material.001"]}
          position={[0.684, -0.158, 0.681]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane512.geometry}
          material={materials["material.001"]}
          position={[-0.562, 0.462, 0.673]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane513.geometry}
          material={materials["material.001"]}
          position={[-0.501, -0.422, 0.732]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane514.geometry}
          material={materials["material.001"]}
          position={[-0.37, -0.71, 0.6]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane515.geometry}
          material={materials["material.001"]}
          position={[-0.124, -0.056, 0.974]}
          scale={-3.412}
        />
        <mesh
          geometry={nodes.Plane516.geometry}
          material={materials["material.001"]}
          position={[0.677, -0.7, 0.116]}
          scale={-3.412}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/earth.glb");
