/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 finalAnim.glb 
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function AnimaFinal(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/finalAnim.glb");
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    Object.values(actions).forEach((action) => {
      action.timeScale = 0.8;
      action.play();
    });
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Empty001" position={[0, 1.218, 0]}>
          <group
            name="Empty"
            position={[0, -1.218, 0]}
            rotation={[-Math.PI, 0.213, -Math.PI]}
          >
            <group name="Apple" rotation={[-Math.PI, 0.154, -Math.PI]}>
              <mesh
                name="Cube020"
                geometry={nodes.Cube020.geometry}
                material={materials.DarkRed}
              />
              <mesh
                name="Cube020_1"
                geometry={nodes.Cube020_1.geometry}
                material={materials.DarkBrown}
              />
              <mesh
                name="Cube020_2"
                geometry={nodes.Cube020_2.geometry}
                material={materials.DarkGreen}
              />
            </group>
            <group name="BurgerLarge" scale={0}>
              <mesh
                name="Plane005"
                geometry={nodes.Plane005.geometry}
                material={materials.LightGreen}
              />
              <mesh
                name="Plane005_1"
                geometry={nodes.Plane005_1.geometry}
                material={materials.Yellow}
              />
              <mesh
                name="Plane005_2"
                geometry={nodes.Plane005_2.geometry}
                material={materials.Brown}
              />
              <mesh
                name="Plane005_3"
                geometry={nodes.Plane005_3.geometry}
                material={materials.Red}
              />
              <mesh
                name="Plane005_4"
                geometry={nodes.Plane005_4.geometry}
                material={materials.LightYellow}
              />
              <mesh
                name="Plane005_5"
                geometry={nodes.Plane005_5.geometry}
                material={materials.White}
              />
            </group>
            <group name="ChickenLeg" scale={0}>
              <mesh
                name="Cube048"
                geometry={nodes.Cube048.geometry}
                material={materials["DarkBrown.001"]}
              />
              <mesh
                name="Cube048_1"
                geometry={nodes.Cube048_1.geometry}
                material={materials.Beige}
              />
            </group>
            <group name="CookingPot2_Soup" scale={0}>
              <mesh
                name="Cylinder016"
                geometry={nodes.Cylinder016.geometry}
                material={materials.Grey}
              />
              <mesh
                name="Cylinder016_1"
                geometry={nodes.Cylinder016_1.geometry}
                material={materials["Brown.001"]}
              />
            </group>
            <group name="Cupcake" scale={0}>
              <mesh
                name="Cylinder026"
                geometry={nodes.Cylinder026.geometry}
                material={materials["LightYellow.001"]}
              />
              <mesh
                name="Cylinder026_1"
                geometry={nodes.Cylinder026_1.geometry}
                material={materials.Pink}
              />
              <mesh
                name="Cylinder026_2"
                geometry={nodes.Cylinder026_2.geometry}
                material={materials["DarkBrown.002"]}
              />
            </group>
            <group name="Pancakes_Stack" scale={0}>
              <mesh
                name="Cylinder033"
                geometry={nodes.Cylinder033.geometry}
                material={materials.LightBeige}
              />
              <mesh
                name="Cylinder033_1"
                geometry={nodes.Cylinder033_1.geometry}
                material={materials.Light}
              />
              <mesh
                name="Cylinder033_2"
                geometry={nodes.Cylinder033_2.geometry}
                material={materials["Yellow.001"]}
              />
              <mesh
                name="Cylinder033_3"
                geometry={nodes.Cylinder033_3.geometry}
                material={materials.Syrup}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/finalAnim.glb");
