/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 Pancakes_Stack.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Pancakes(props) {
  const { nodes, materials } = useGLTF("/models/Pancakes_Stack.glb");
  return (
    <group
      {...props}
      dispose={null}
      position={[3, 0, 0]}
      scale={3}
      rotation-x={(Math.PI / 180) * 20}
    >
      <mesh
        geometry={nodes.Cylinder033.geometry}
        material={materials.LightBeige}
      />
      <mesh
        geometry={nodes.Cylinder033_1.geometry}
        material={materials.Light}
      />
      <mesh
        geometry={nodes.Cylinder033_2.geometry}
        material={materials.Yellow}
      />
      <mesh
        geometry={nodes.Cylinder033_3.geometry}
        material={materials.Syrup}
      />
    </group>
  );
}

useGLTF.preload("/Pancakes_Stack.glb");
