/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Pumpkin.glb 
*/

import React, { useRef } from "react";
import { OrbitControls, useGLTF } from "@react-three/drei";

export function Pumpkin(props) {
  const { nodes, materials } = useGLTF("/models/Pumpkin.glb");
  return (
    <group
      {...props}
      dispose={null}
      scale={3}
      position={[2.5, -1, 0]}
      rotation-y={Math.PI * 0.75}
      rotation-x={Math.PI * 0.1}
    >
      <mesh geometry={nodes.Cylinder047.geometry} material={materials.Brown} />
      <mesh
        geometry={nodes.Cylinder047_1.geometry}
        material={materials.Orange}
      />
    </group>
  );
}

useGLTF.preload("/Pumpkin.glb");
