/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 q_mark.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function QMark(props) {
  const { nodes, materials } = useGLTF("/models/q_mark.glb");
  return (
    <group {...props} dispose={null} scale={0.02} position={[0.3, -1.13, 0]}>
      <ambientLight />

      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.svgMeshShape3.geometry}
          material={materials["aiStandardSurface2.001"]}
          position={[-4.752, -0.788, -2]}
          scale={[1, 1.575, 1]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/q_mark.glb");
