/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 pepper.gltf 
*/

import React, { useRef } from "react";
import { shaderMaterial, useGLTF } from "@react-three/drei";
import { extend } from "@react-three/fiber";
import glsl from "glslify";
const PanidyandShaderMaterial = shaderMaterial(
  {},

  glsl`
   varying vec3 vPosition;

      void main() {
        vPosition = position;
        gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
      } 
  `,
  glsl`
    varying vec3 vPosition;

    void main() {
      float opacity =smoothstep(-1.0,1.0,vPosition.z*28.528);
      gl_FragColor = vec4(0.238, 0.162, 0.325, opacity);
    } 
  `
);
extend({ PanidyandShaderMaterial });
export function Pepper(props) {
  const { nodes, materials } = useGLTF("/models/cards/pepper.gltf");
  return (
    <group {...props} dispose={null} position={[0, 0, 0]}>
      {/* <axesHelper args={[5]} /> */}
      <mesh
        geometry={nodes.Text.geometry}
        material={materials["Material.002"]}
        position={[0, -0.795, 0.094]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.302}
      />
      <mesh
        geometry={nodes.Text001.geometry}
        material={materials["Material.002"]}
        position={[0, -1.166, 0.086]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.369}
      />
      <mesh
        geometry={nodes.Text002.geometry}
        material={materials["Material.002"]}
        position={[0, -1.647, 0.107]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.182}
      />
      <group
        position={[0, 0.534, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={5.088}
      >
        <mesh
          geometry={nodes.model038_1.geometry}
          material={materials["mat21.001"]}
        />
        <mesh
          geometry={nodes.model038_2.geometry}
          material={materials["mat15.001"]}
        />
        <mesh
          geometry={nodes.model038_3.geometry}
          material={materials["mat24.001"]}
        />
        <mesh
          geometry={nodes.model038_4.geometry}
          material={materials["mat25.001"]}
        />
        <mesh
          geometry={nodes.model038_5.geometry}
          material={materials["mat23.001"]}
        />
        <mesh
          geometry={nodes.model038_6.geometry}
          material={materials["mat22.001"]}
        />
        <mesh
          geometry={nodes.model038_7.geometry}
          material={materials["mat17.001"]}
        />
      </group>
      <mesh
        geometry={nodes.Curve.geometry}
        material={materials["Material.004"]}
        position={[-0.004, 0.003, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[28.527, 28.528, 28.528]}
      />
      <mesh
        geometry={nodes.Curve002.geometry}
        material={materials["Material.006"]}
        position={[0, -1.934, 0.108]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={29.821}
      />
      <mesh
        geometry={nodes.Curve007.geometry}
        position={[-0.004, 0.003, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[28.031, 28.528, 28.031]}
      >
        <panidyandShaderMaterial transparent />
      </mesh>
      <mesh
        geometry={nodes.Curve001.geometry}
        material={materials["Material.006"]}
        position={[0.66, -1.934, 0.125]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={34.117}
      />
      <mesh
        geometry={nodes.Curve003.geometry}
        material={materials["Material.006"]}
        position={[-0.33, -1.934, 0.108]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={29.821}
      />
      <mesh
        geometry={nodes.Curve004.geometry}
        material={materials["Material.006"]}
        position={[-0.66, -1.934, 0.108]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={29.821}
      />
      <mesh
        geometry={nodes.Curve005.geometry}
        material={materials["Material.006"]}
        position={[0.33, -1.934, 0.108]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={29.821}
      />
    </group>
  );
}

useGLTF.preload("/pepper.gltf");
